### PR TITLE
Create package.xml

### PR DESCRIPTION
**Pull request by chennes**
This is an example of the new package.xml metadata file format. To use it, just update the elements that don't suit your release (I just made up a version number here, and I don't have your email address, so you'll want to update those). For complete documentation of the options, see https://wiki.freecadweb.org/Package_Metadata

### CODE REVIEW

**Comment by luzpaz** [comment]
@podestplatz ping

**Comment by podestplatz** [comment]
Hi @chennes, 

thank you for your work on this repo and this pull request, I really appreciate your interest!
Sorry for me getting back so late on this PR. I am not able to support this repo, and have not for quite some time now. 
Since you have put in the work to contribute to this repo, I'll merge it.

**Comment by luzpaz** [comment]
>  I am not able to support this repo, and have not for quite some time now.

good to know. How should we proceed then? Clone this repo in to the FreeCAD GH org?

**Comment by podestplatz** [comment]
I think you're a better judge than me on whether cloning it into the FreeCAD GH org is reasonable or not. So if you deem this a reasonable option then I am all for it.

**Comment by luzpaz** [comment]
@yorikvanhavre please weigh-in. Thanks!

**Pull request merged**
